# Generated by Django 3.2 on 2021-04-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_corredor_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='user',
            new_name='usuario',
        ),
    ]
