# Generated by Django 3.2 on 2021-04-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210419_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corredor',
        ),
    ]
