# Generated by Django 3.2 on 2021-04-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categoria_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conferencia', models.DateTimeField(auto_now_add=True)),
                ('codigo_barras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produto')),
            ],
        ),
        migrations.AlterModelOptions(
            name='corredor',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Corredores'},
        ),
        migrations.CreateModel(
            name='Validade_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_validade', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
                ('codigo_barras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produto')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conferencia')),
            ],
        ),
        migrations.AddField(
            model_name='conferencia',
            name='corredor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.corredor'),
        ),
        migrations.AddField(
            model_name='conferencia',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funcionario'),
        ),
    ]
