# Generated by Django 3.2 on 2021-04-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210419_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='codigo_barras',
        ),
    ]
