# Generated by Django 3.2 on 2021-04-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_conferencia_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='data_conferencia',
            field=models.DateField(auto_now_add=True),
        ),
    ]
