# Generated by Django 3.2 on 2021-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_conferencia_data_conferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validade_produto',
            name='data_validade',
            field=models.DateField(),
        ),
    ]
