# Generated by Django 3.2 on 2021-04-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_validade_produto_data_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filial_corredor', to='main.filial'),
        ),
    ]
