# Generated by Django 3.2 on 2021-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210420_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='filial',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
