# Generated by Django 3.2 on 2021-04-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_funcionario_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validade_produto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='validade_produto',
            name='conferencia',
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Filiais'},
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Validade_Produto',
        ),
    ]
